# ===================================================================
# DICIONÁRIO DOS NOMES DAS COLUNAS
# ===================================================================
COLUMN_MAPPING = {
    "CO_MUNICIPIO_ESC": "Cód. Município Escola",
    "CO_MUNICIPIO_PROVA": "Cód. do Município da Prova",
    "CO_PROVA_CH": "Cód. da Prova de História",
    "CO_PROVA_CN": "Cód. da Prova de Ciências da Natureza",
    "CO_PROVA_LC": "Cód. da Prova de Linguagens e Códigos",
    "CO_PROVA_MT": "Cód. da Prova de Matemática",
    "CO_UF_ENTIDADE_CERTIFICACAO": "Cód. UF Certificação",
    "CO_UF_ESC": "Cód. da UF da Escola",
    "CO_UF_PROVA": "Cód. da UF da Prova",
    "ESCOLARIDADE_PAIS_AGRUPADO": "Escolaridade dos Pais",
    "FLAG_CANDIDATO_ADULTO": "Adulto?",
    "FLAG_CAPITAL": "Candidato realizou a prova na capital do estado?",
    "INDICADOR_ABSENTEISMO": "Presença",
    "INDICADOR_REDACAO_ZERADA": "Redação Zerada?",
    "INDICE_ACESSO_TECNOLOGIA": "Acesso à Tecnologia",
    "IN_CERTIFICADO": "Certificado?",
    "IN_TREINEIRO": "Treineiro?",
    "MEDIA_GERAL": "Média Geral",
    "MEDIA_OBJETIVAS": "Média Questões Objetivas",
    "NO_ENTIDADE_CERTIFICACAO": "Nome Entidade Certificação",
    "NO_MUNICIPIO_ESC": "Nome do Município da Escola",
    "NU_ANO": "Ano",
    "NU_INSCRICAO": "Nº de Inscrição",
    "NU_NOTA_CH": "Nota de História",
    "NU_NOTA_CN": "Nota de Ciências da Natureza",
    "NU_NOTA_COMP1": "Nota Competência 1",
    "NU_NOTA_COMP2": "Nota Competência 2",
    "NU_NOTA_COMP3": "Nota Competência 3",
    "NU_NOTA_COMP4": "Nota Competência 4",
    "NU_NOTA_COMP5": "Nota Competência 5",
    "NU_NOTA_LC": "Nota de Linguagens e Códigos",
    "NU_NOTA_MT": "Nota de Matemática",
    "NU_NOTA_REDACAO": "Nota da Redação",
    "REGIAO_CANDIDATO": "Região do Candidato",
    "REGIAO_ESCOLA": "Região da Escola do Candidato",
    "RENDA_FAMILIAR": "Renda Familiar",
    "SG_UF_ENTIDADE_CERTIFICACAO": "UF Entidade Certificação",
    "SG_UF_ESC": "Sigla da UF da Escola",
    "SG_UF_PROVA": "Sigla da UF da Prova",
    "TEMPO_FORA_ESCOLA": "Tempo Fora da Escola",
    "TIPO_ESCOLA_AGRUPADO": "Tipo da Escola",
    "TP_ANO_CONCLUIU": "Ano de Conclusão",
    "TP_COR_RACA": "Cor/Raça",
    "TP_DEPENDENCIA_ADM_ESC": "Tipo de Dependência Administrativa da Escola",
    "TP_ENSINO": "Tipo de Ensino",
    "TP_ESCOLA": "Tipo de Escola",
    "TP_ESTADO_CIVIL": "Estado Civil",
    "TP_FAIXA_ETARIA": "Faixa Etária",
    "TP_LINGUA": "Tipo de Língua",
    "TP_LOCALIZACAO_ESC": "Localização da Escola",
    "TP_NACIONALIDADE": "Nacionalidade",
    "TP_PRESENCA_CH": "Presença em História",
    "TP_PRESENCA_CN": "Presença em Ciências da Natureza",
    "TP_PRESENCA_LC": "Presença em Linguagens e Códigos",
    "TP_PRESENCA_MT": "Presença em Matemática",
    "TP_SEXO": "Sexo",
    "TP_SIT_FUNC_ESC": "Situação Funcional da Escola",
    "TP_STATUS_REDACAO": "Status da Redação",
    "TP_ST_CONCLUSAO": "Situação de Conclusão",
    "TX_GABARITO_CH": "Gabarito de História",
    "TX_GABARITO_CN": "Gabarito de Ciências da Natureza",
    "TX_GABARITO_LC": "Gabarito de Linguagens e Códigos",
    "TX_GABARITO_MT": "Gabarito de Matemática",
    "TX_RESPOSTAS_CH": "Respostas de História",
    "TX_RESPOSTAS_CN": "Respostas de Ciências da Natureza",
    "TX_RESPOSTAS_LC": "Respostas de Linguagens e Códigos",
    "TX_RESPOSTAS_MT": "Respostas de Matemática"
}